### ISSUE TITLE
Redundant .gitignore

### ISSUE THREAD

**Issue by rcass** [markfloress/Project-4#2]
Inside the plugins folder there is a .gitignore, since we already have a gitignore in the root of our project (the root of the wp-content), the one in the plugins folder is unnecessary!

- [x] Delete .gitignore in the plugin folder (it is extra)

**Comment by markfloress** [comment]
removed!

**Comment by rcass** [comment]
The other plugin still has a .gitignore that needs to be deleted! So this ticket is 50% resolved atm
